# Generated by Django 3.2.6 on 2021-08-26 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('budget', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('montant', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('solde', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('debit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('credit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.DateField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('montant', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('solde', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('credit', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('debit', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_initial', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('debit', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('credit', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('date_debut', models.DateField(auto_now=True)),
                ('bilan_pdf', models.FileField(null=True, upload_to='user_directory_path', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, max_length=60, null=True)),
                ('etat', models.CharField(choices=[('non traitée', 'non traitée'), ('refusée', 'refusée'), ('acceptée', 'acceptée')], default='non traitée', max_length=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_finace',
            fields=[
                ('numdoc', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_pdf', models.FileField(null=True, upload_to='user_directory_path', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('type', models.CharField(choices=[('fiche de paie', 'fiche de paie'), ('attestation de solde', 'attestation de solde'), ('relevé de compte', 'relevé de compte'), ('reçu de cheque', 'reçu de cheque')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(null=True)),
                ('adresse', models.CharField(max_length=400)),
                ('poste', models.CharField(max_length=100)),
                ('ccp', models.IntegerField(verbose_name='num compte postal')),
                ('nss', models.IntegerField(verbose_name='num sécurité sociale')),
                ('email', models.EmailField(max_length=254)),
                ('num_tel', models.IntegerField(verbose_name='num tel')),
                ('date_deb', models.DateField()),
                ('date_sortie', models.DateField()),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('sex', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('nbchap', models.IntegerField(blank=True, default=0, null=True)),
                ('budget', models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('budget_restant', models.PositiveIntegerField(null=True)),
                ('solde', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('debit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('credit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('date', models.DateField(auto_now_add=True)),
                ('justificatif', models.TextField(null=True)),
                ('etat', models.CharField(choices=[('en cours', 'en cours'), ('refusee', 'refusee'), ('acceptee', 'acceptee')], default='en cours', max_length=8)),
                ('document', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('contenu', models.TextField()),
                ('idcompteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subvention', models.CharField(max_length=500)),
                ('montant', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('description', models.CharField(max_length=300)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='images/default_image.jpg', null=True, upload_to='images/')),
                ('employe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse_demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=1000)),
                ('demande', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('contenu', models.TextField()),
                ('idcompteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
            ],
        ),
        migrations.CreateModel(
            name='remboursement_pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mois', models.IntegerField(null=True)),
                ('montant', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('pret', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pret')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('virement', 'virement'), ('especes', 'especes'), ('cheque', 'cheque')], max_length=8)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='files')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idfac', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('fac_pdf', models.FileField(null=True, upload_to='user_directory_path', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('mode_paiement', models.CharField(choices=[('cach', 'cach'), ('versement bancaire', 'versement bancaire')], max_length=20)),
                ('idcompteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('numdemande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('nbart', models.IntegerField(blank=True, default=0, null=True)),
                ('budget', models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('budget_restant', models.PositiveIntegerField(null=True)),
                ('solde', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('debit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('credit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('partie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.partie')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.chapitre'),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200, null=True)),
                ('contenu', models.TextField(null=True)),
                ('date_debut', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateTimeField()),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
