# Generated by Django 3.2.6 on 2021-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('Virement', 'Virement'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque')], max_length=8),
        ),
    ]
