# Generated by Django 3.2.6 on 2021-08-31 15:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_annonce_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='solde',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='annee',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='solde',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='partie',
            name='solde',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
