# Generated by Django 3.2.6 on 2021-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210831_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='annee',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
