# Generated by Django 3.2.6 on 2021-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210831_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='mode_paiement',
            field=models.CharField(choices=[('Virement', 'Virement'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque')], max_length=8, null=True),
        ),
    ]
