# Generated by Django 3.2.6 on 2021-09-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210903_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_paiement',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
