# Generated by Django 3.2.6 on 2021-09-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210903_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_paiement',
            field=models.DateTimeField(null=True),
        ),
    ]
