# Generated by Django 3.2.6 on 2021-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_demande_date_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['nom']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=5),
        ),
    ]
