# Generated by Django 3.2.6 on 2021-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210905_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='objet',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='contenu',
        ),
        migrations.AddField(
            model_name='annonce',
            name='detail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
