# Generated by Django 3.2.6 on 2021-09-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210906_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_debut',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
