# Generated by Django 3.2.6 on 2021-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210906_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
