# Generated by Django 3.2.6 on 2021-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_annonce_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
