# Generated by Django 3.2.6 on 2021-09-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_annonce_date_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_deb',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_sortie',
        ),
    ]
