# Generated by Django 3.2.6 on 2021-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_article_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.CharField(max_length=200),
        ),
    ]
