# Generated by Django 3.2.6 on 2021-09-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_partie_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='partie',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
