# Generated by Django 3.2.6 on 2021-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='titre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
