# Generated by Django 3.2.6 on 2021-09-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_annonce_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='remboursement_pret',
            new_name='Remboursement',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='document',
        ),
        migrations.AlterField(
            model_name='pret',
            name='etat',
            field=models.CharField(choices=[('non traitée', 'non traitée'), ('refusée', 'refusée'), ('acceptée', 'acceptée')], default='non traitée', max_length=12),
        ),
        migrations.CreateModel(
            name='Fichier_Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='files')),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pret')),
            ],
        ),
    ]
