# Generated by Django 3.2.6 on 2021-09-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20210909_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['nom', 'prenom']},
        ),
    ]
