# Generated by Django 3.2.6 on 2021-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_employee_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pret',
            name='justificatif',
        ),
        migrations.AddField(
            model_name='pret',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='mode_paiement',
            field=models.CharField(choices=[('Virement', 'Virement'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque')], max_length=8, null=True),
        ),
    ]
