# Generated by Django 3.2.6 on 2021-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20210909_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='date_paiement',
            field=models.DateTimeField(null=True),
        ),
    ]
