# Generated by Django 3.2.6 on 2021-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20210910_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_debut',
            field=models.DateTimeField(),
        ),
    ]
