# Generated by Django 3.2.6 on 2021-09-11 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0037_tirage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='admis',
            field=models.ManyToManyField(related_name='admis', to=settings.AUTH_USER_MODEL),
        ),
    ]
