# Generated by Django 3.2.6 on 2021-09-11 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0038_inscription_admis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='admis',
        ),
        migrations.AddField(
            model_name='annonce',
            name='admis',
            field=models.ManyToManyField(related_name='admis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tirage',
        ),
    ]
