# Generated by Django 3.2.6 on 2021-09-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_auto_20210911_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='montant',
            field=models.IntegerField(null=True),
        ),
    ]
