# Generated by Django 3.2.6 on 2021-09-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_annonce_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='detail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
