# Generated by Django 3.2.6 on 2021-09-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_auto_20210912_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='montant',
            new_name='budget',
        ),
    ]
