# Generated by Django 3.2.6 on 2021-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_auto_20210913_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='montant',
            field=models.IntegerField(null=True),
        ),
    ]
