# Generated by Django 3.2.6 on 2021-09-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_inscription_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='date_entree',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='description',
        ),
        migrations.AddField(
            model_name='recette',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
